### ISSUE TITLE
Deprecation of ToLayoutConstraints()

### ISSUE THREAD

**Issue by mrtnkrstn** [FluentLayout/Cirrious.FluentLayout#27]
I use `ToLayoutConstraints()` in the following manner:

`FluentLayout heightFluentLayout = view.Height().EqualTo(100);`
`NSLayoutConstraint heightConstraint = heightFluentLayout.ToLayoutConstraints().First();`

(where `view` is some `UIView`), and then add this constraint to the parent view. I can now use `heightConstraint` to change the height of the view, e.g. as follows:

`heightConstraint.Constant = 130;`

Now that `ToLayoutConstraints()` is destined for obsoletion, is there another way to achieve the above?

Thanks!

**Comment by gshackles** [comment]
Yeah, you can now simply manipulate `heightFluentLayout.Constant` which will be propagated down to the underlying constraint. You can find more details in my blog post here: http://gregshackles.com/fluentlayout-2-5/
