### ISSUE TITLE
Width equal to height

### ISSUE THREAD

**Issue by zjxeditor** [FluentLayout/Cirrious.FluentLayout#30]
Hi, how can we make a square constraint? In other words, a control's or view's width equal to its own height. I don't find any code to make it in the source code.

**Comment by xleon** [comment]
```
avatar.WithSameHeight(panel),
avatar.Width().EqualTo().HeightOf(avatar)
```

**Comment by zjxeditor** [comment]
Oh, I am too stupid, lol ~~~

**Comment by gshackles** [comment]
Thanks, Diego! :smile:
