### ISSUE TITLE
What's iOS supported?

### ISSUE THREAD

**Issue by hoangwy** [FluentLayout/Cirrious.FluentLayout#34]
Hi,
What's iOS supported?
Thanks so much!

**Comment by Cheesebaron** [comment]
All that support constraints, so iOS 6 and up?

**Comment by gshackles** [comment]
Technically iOS 6 but in some cases it depends which methods you're trying to use. Over time some extensions have made their way into FluentLayout that require newer versions of iOS. One example is [`LeadingMarginOf`](https://github.com/FluentLayout/Cirrious.FluentLayout/blob/master/Cirrious.FluentLayout/FluentLayout.cs#L193) which [requires iOS 8](https://developer.xamarin.com/api/field/UIKit.NSLayoutAttribute.LeadingMargin/). At some point we should go through each method and add the proper attributes to specify which versions are supported.

In the meantime, most of the library should work with iOS 6 and 7+, with some exceptions as shown requiring 8+.
