### ISSUE TITLE
Not possible to relate width to height?

### ISSUE THREAD

**Issue by Cheesebaron** [FluentLayout/Cirrious.FluentLayout#35]
Usually if I want a square which is as high as it is wide I do something like this:

```
AddConstraint (NSLayoutConstraint.Create (view, NSLayoutAttribute.Height, 
    NSLayoutRelation.Equal, view, NSLayoutAttribute.Width, 1, 0));
```

However, I can't seem to see a way to do exactly this with FluentLayout.

I only see methods to replicate another views bounds, with the methods prefixed with `WithSame` or `WithRelative`. Or you can position the view at top, bottom, left or right of a view. However, there are no expressions to add the constraint above?

**Comment by xleon** [comment]
something.Width().EqualTo().HeightOf(something)

**Comment by Cheesebaron** [comment]
Ah! I am blind :D Thanks!
