### ISSUE TITLE
Sample for UiTableViewCell

### ISSUE THREAD

**Issue by bondarenkod** [FluentLayout/Cirrious.FluentLayout#37]
Hi! Is there anywhere sample how to use FL for uitableviewcells?
--------------
Sorry) My bad. Small sample is here - 
https://github.com/bondarenkod/xam-ios-fluent-layout-test/blob/master/TableTest/TableTest/RuntimeCell.cs

**Comment by Cheesebaron** [comment]
I would try _not_ to use constraints for cells, especially if you want smooth scrolling with semi complicated cells.

**Comment by bondarenkod** [comment]
@Cheesebaron how to create cells without constraints?
