### ISSUE TITLE
Nuget package is out of date

### ISSUE THREAD

**Issue by srs506** [FluentLayout/Cirrious.FluentLayout#40]
I added the Nuget package (2.5.0) to my iOS project , but noticed that it hasn't been updated to include ToLeftMargin, ToRightMargin, etc.

**Comment by gshackles** [comment]
Whoops, thanks for the callout on that. I think at the time I was expecting to push some other changes before publishing a new version, but clearly that didn't happen. [I just pushed a 2.6.0 to NuGet](https://www.nuget.org/packages/Cirrious.FluentLayout/2.6.0), so you should be able to use those methods now.

Thanks again!

**Comment by srs506** [comment]
Thank you!
