### ISSUE TITLE
Integrate Cake and general improvements

### ISSUE THREAD

**Issue by jzeferino** [FluentLayout/Cirrious.FluentLayout#51]
I wonder if you are interested in help to integrate Cake and make some improvements/updates to the code.

**Comment by jzeferino** [comment]
Regarding the cake, its just a personal flavor over FAKE, but if you're cool with FAKE, awesome.

Regarding other code improvements, could I step in?

**Comment by gshackles** [comment]
Of course, contributions always welcome! I'm going to close this issue out, but definitely feel free to open any issues (or PRs) around changes you'd like to see/make. Thanks! 😄
