### ISSUE TITLE
Support for earlier verions of iOS than 16.0

### ISSUE THREAD

**Issue by JimWilcox3** [FluentLayout/Cirrious.FluentLayout#68]
It is telling me that it only supports net6.0-ios16.0. Visual Studio only goes up to net6.0-ios15.4. Is there a workaround for this?

**Comment by Cheesebaron** [comment]
Isn't it just a warning? Or is it refusing to install the package?

**Comment by JimWilcox3** [comment]
It won't install the package.  It says it requires net6.0-ios16.0.  I tried editing the project file and putting it in there, but then it won't compile and makes the same complaint.

**Comment by JimWilcox3** [comment]
When I updated Visual Studio yesterday, it included iOS-16, so this is no longer an issue.
